development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "2426aa44ac98575dbf710acd29650276acfb29c91edd74c0a1f9b4e995d228ac"
  signature_expiration: 3600 # one hour
